Comp add edit header
ndwilliamson123/instock-project-team-2-client pull request #11
Opened 2022-10-19 04:31 UTC by SomeViet

Creating to subheader for Add and Edit pages

2022-10-19 23:52 UTC, ndwilliamson123 requested changes
Code looks good other than the use of index.js

If someone can take a look at it visually, please do. Or I can review later tonight.

2022-10-19 23:52 UTC, ndwilliamson123 commented on src/App.js
> +import AddEditSubheader from "./components/AddEditSubheader/AddEditSubheader";
We should add the AddEditSubheader component to the index.js file so we can import it on line 3

import { Footer, AddEditSubheader } from "./components/index";

2022-10-20 03:38 UTC, SomeViet commented on src/App.js
> +import AddEditSubheader from "./components/AddEditSubheader/AddEditSubheader";
Added component to index.js file

2022-10-20 03:52 UTC, ndwilliamson123 approved these changes
LGTM

2022-10-20 03:52 UTC, merged