A22ab2 6
ndwilliamson123/instock-project-team-2-client pull request #4
Opened 2022-10-14 23:23 UTC by ndwilliamson123

Hey guys! I created the Warehouse List and Warehouse List Item components. Some of the styling is manually done until the Sass vars/mixins are available. (Some of the styling is also not done like colors for now).

Please let me know if you have any suggestions or questions.

2022-10-15 21:20 UTC, ankurbag commented on src/components/WarehouseList/WarehouseList.js
> +      <div className="warehouse-list__columns">
I was wondering if we can break this into smaller components.

2022-10-16 01:45 UTC, ankurbag requested changes
Super like :) Please take care of the changes, and then we can approve it!

2022-10-20 02:49 UTC, ndwilliamson123 commented on src/components/WarehouseList/WarehouseList.js
> +      <div className="warehouse-list__columns">
I broke these down into two more components as requested. The header is reusable for the other inventory main page so it is called MainSubHeader.

2022-10-20 04:28 UTC, SomeViet commented on src/components/WarehousesListColumns/WarehousesListColumns.js
> +            </div>
if we have time, figure out sort functionality; I don't think we will have time, so ignore I guess.

2022-10-20 04:51 UTC, SomeViet approved these changes
As changes are minor and visual, I have approved the merge. Please commit if and after changes are done.

As API is not connected yet, do not close ticket until back-end is hooked up.

2022-10-20 04:51 UTC, SomeViet commented on src/components/WarehousesListItem/WarehousesListItem.scss
> +
Minor visual edit:
currently, the borders of the table touch each other - suggested edit. 
**column-gap: 32px**; would give it some room (estimated from figma).

This causes the boxes to do some weird collapsing at 350px, but I think that's acceptable since the emails won't shrink.

referencing - https://css-tricks.com/snippets/css/complete-guide-grid/#prop-grid-template-columns-rows

2022-10-20 04:51 UTC, SomeViet commented on src/components/MainSubHeader/MainSubHeader.js
> +                <Link to="/warehouses/add">
I would just note this is a dummy searchbar, as we haven't learned how to do search bars yet.

This could also be a component, but we can do that in refactoring if needed.

2022-10-20 17:33 UTC, ankurbag commented
Like Like LIke! 
Thank you for working on this

2022-10-20 17:33 UTC, ankurbag approved these changes

2022-10-20 20:01 UTC, merged