A22AB2-2 - Front-End: Sass Variables, Mixins, Breakpoints, Colors and Font-face
ndwilliamson123/instock-project-team-2-client pull request #5
Opened 2022-10-15 23:11 UTC by pauldeleonsg

for desktop (at the moment). partial styling:

- styles
-- partials
--- _fonts.scss
--- _global.scss
--- _variables.scss

-- Anchor.scss
-- Footer.scss
-- Form.scss
-- Header.scss
-- Main.scss
-- Modal.scss
-- Table.scss

- App.scss

2022-10-16 01:38 UTC, ankurbag commented on package-lock.json
>          "axios": "^1.1.2",
Please put `package-lock` in git-ignore file

2022-10-16 01:40 UTC, ankurbag commented on src/components/InventoryAll/InventoryAll.js
> +                                    src={require('../../assets/icons/sort-24px.svg').default}
Just a nit-pick : We can keep this in a const variable, and then use it here

2022-10-16 01:40 UTC, ankurbag commented on src/components/InventoryAll/InventoryAll.js
> +                                    alt='Sort' className="iconAction" />
Same comment as above

2022-10-16 01:41 UTC, ankurbag commented on src/components/InventoryAll/InventoryAll.js
> +//references:
Super like about the documentation mention. I am just wondering if we can move this up :)

2022-10-16 01:42 UTC, ankurbag commented on src/styles/partials/_variables.scss
> +
nit-pick : lot of extra spaces here :)

2022-10-16 01:43 UTC, ankurbag commented on src/styles/partials/_variables.scss
> +
nit-pick : lot of extra line here :)

2022-10-16 01:43 UTC, ankurbag commented on src/styles/partials/_variables.scss
> +
nit-pick : lot of extra spaces here :)

2022-10-16 01:43 UTC, ankurbag commented on src/styles/partials/_variables.scss
> +//layout fix
I was wondering if Is this left intentionally?

2022-10-16 01:44 UTC, ankurbag requested changes
Kindly add `bin` folder in the git ignore aswell

2022-10-16 01:44 UTC, ankurbag commented
KIndly take care of `merge cnflicts`

2022-10-16 01:47 UTC, ankurbag commented
Thank you for working on these tasks :) Super like!!!

2022-10-16 20:17 UTC, saint-fox1 commented on src/components/InventoryAll/InventoryAll.js
> +                            <span className='tableAction'>
nit-pick: it should be 'table__action' as per BEM

2022-10-16 20:17 UTC, saint-fox1 commented on src/components/InventoryAll/InventoryAll.js
> +                                    alt='Sort' className="iconAction" />
we should stick to one type of styling - kebab for css and camecase for js (suggestion I posted in slack, which seems to be in line with others) so consider using 'icon-action' instead

2022-10-16 20:17 UTC, saint-fox1 commented on src/components/Mockup/Modal.js
> +        <>
you don't need <> since you have only one div inside

2022-10-16 20:17 UTC, saint-fox1 commented on src/components/Mockup/Modal.js
> +            <div className='modalContainer' id='modalMsg'>
try to adopt BEM here using this example https://gist.github.com/asainz/105c8a2014a28a8dbcd8. You should have model class before model__container class

2022-10-16 20:17 UTC, saint-fox1 commented on src/components/Mockup/Modal.js
> +                        <a href="#close" className="anchorModalClose">X</a>
maybe convert to kebab case to be consistent

2022-10-16 20:17 UTC, saint-fox1 commented on src/components/Mockup/Modal.js
> +                    <div className='modal__buttonbar'>
convert to modal__button-bar

2022-10-16 20:17 UTC, saint-fox1 commented on src/components/PageTitle/PageTitle.js
> +                    <div className='pagetitle__subitem'>
maybe can come up with a better name for this class that only contains a button

2022-10-16 20:17 UTC, saint-fox1 commented on src/styles/Modal.scss
> +    &__body {
I think we should try to avoid applying styling directly to body. Maybe we can apply it to a class or set this styling in app.js?

2022-10-16 20:22 UTC, saint-fox1 reviewed
Overall looks great, but two things that I noticed: naming of the classes is not consistent and you did things that are not part of this particular ticket, which means there is a lot of functionality and pages to review. It is very hard to review when I don't know what exactly you were focusing on in this ticket. Also, it seems like you did my ticket for header component. Break points are missing.

2022-10-16 23:33 UTC, SomeViet requested changes
Hi Paul, this ticket was only to push the partials up. As you have incorporated all your other features, we will be unable to push this, as it contains other features, which should have been done on other branches. Svetlana has also commented regarding this.

Please remove all your other features, and only push the partials for this (Probably create another ticket).

Thanks!

2022-10-18 01:21 UTC, saint-fox1 commented on src/styles/partials/_variables.scss
> +$bgColorBlack : #13182C;
Color names need to be changed to actual color names 
![image](https://user-images.githubusercontent.com/105024671/196313025-2ed95c55-3a45-4a2d-b773-2d6692eb2f57.png)

2022-10-21 01:57 UTC, closed without merging